darchr/gem5

- configs/learning_gem5/part1/simple.py
- configs/learning_gem5/part1/two_level.py
- configs/learning_gem5/part2/simple_cache.py
- configs/learning_gem5/part2/simple_memobj.py
Change-Id: I6da0e3a2ec5801b382f5f76f94a1c0aad492f44c
> configs,learning-gem5: Fixed hello binary location

- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_cpu.hh
Change-Id: I5d5e05fa87bad7586af793b44311955517b89724
> [fixup] Fix bug in split writes in SimpleDataflowCPU

- src/cpu/flexcpu/inflight_inst.cc
Change-Id: Ie91d645dbf1d23cd34b963555ac65abca21b081c
> Actually fixes build errors on .fast

- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: I3ee93007a239c1907fed6aed0b9a12b0e51d63f7
> cpu: Improved macroop handling

- src/cpu/flexcpu/SConscript
- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: I7ae4d2a3993a7c5bae0ec5d0969b56f31c9feb60
> cpu: Cleanup flexcpu style and improved debug messages

- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: I408fda8a30d3089f7e329e3a64d108b929166b52
> cpu: Add explicit serialization logic to flexcpu

- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: Iaa086224356c454034fdf0b5ed221fca24069c2a
> flexcpu: Added non-operand miscreg access support

- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_cpu.hh
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I752172023a0440e21e9e5963140fc9d89670a329
> flexcpu: Commit dependencies and strict serialization

- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I8e0b48d1938a96cce83386287b970e46846aa572
> flexcpu: Add some stats and callbacks

- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_cpu.hh
- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: Ic9d8f2e8ccb0bd2d5f493181f3d77d0059a0687e
> cpu-flexcpu: Added tracing for debug-flag Exec

- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_cpu.hh
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I83f07fd293c42dd211cbffc72319b5ba68319fc8
> cpu-flexcpu: added an internal thread fetch-buffer

- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: I6b274e275dce49366670ade90faa180f3b95fc9a
> cpu-flex: Store at commit time

- src/cpu/flexcpu/SConscript
- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_cpu.hh
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
I know you're not ready for this PR, but I'd like to make some comments on the code.
> Add Branch Predictor functionality

- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I211d262d9ef6683a5308bcf8511dccb560090281
> flexcpu: Add per cycle stats to thread

- src/cpu/flexcpu/simple_dataflow_cpu.cc
Change-Id: I5fdc47d47e90a5717178720e22a411c7c84688eb
> cpu-flex: fix execution_latency parameterization

- src/cpu/flexcpu/SConscript
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: If58d627718036742af228adc7d4aec6d04762640
> cpu-flex: Added whole-buffer debug dump

- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: Ib60b9c72bc54ae7276bef94f8a68ba3062e6d8fd
> cpu-flex: Issue width constraint

- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: Id591857738976397366573e7f4b738f50d8c7d8d
> cpu-flex: inflightInsts buffer size constraint

- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I2ba5944869729ffddf20b9bc128a0342eda50a73
> cpu-flex: allowed independent out-of-order stores

- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_cpu.hh
Change-Id: I0bded287d37394a5229600d619667fea55c22e35
> cpu-flex: zero time microops

- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I5a557a668300efae70b2ed8a839b6a5df62247ab
> cpu-flex: in-order/in-order-superscalar parameters

- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: I75198e89a63d3bb91ec09e1c428d70a9ba9ff04e
> cpu-flex: Added debug messages for source regs

- src/cpu/flexcpu/simple_dataflow_cpu.cc
Change-Id: I3d45ad86726b211bb475ec0fbc73be407b4b97ef
> cpu-flex: Simple mmappedIpr implementation

- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: Ib255c24752d4ceb78b55374509e758f1397e35f3
> cpu-flex: Implemented X86 specific XC functions.

- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: Ifd54add13b5ad017c7b890c1fab9507758f3d45b
> cpu-flex: fixed case where bpd was not released if buffer full

- src/cpu/flexcpu/simple_dataflow_cpu.cc
Change-Id: I6882e1900eb6a9ac7b9572607e40b4ed279aabcf
> cpu-flex: Added missing initialization code for fullsystem

- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: I4d3f51b379973b94819fa82112ed6de173f6bd29
> cpu-flex: Added preprocessor checks to silence warnings w/o trace

- src/cpu/flexcpu/simple_dataflow_thread.cc
Change-Id: Ia04c2d5ddf3a585b764191ad21787618db363ab1
> cpu-flex: Remove some old TODOs, add clarification for a capture

- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I3325d2e598db517c510f34c27f2c5808b8397774
> cpu-flex: Simple thread-driven commit-time interrupts.

- src/cpu/flexcpu/SimpleDataflowCPU.py
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/simple_dataflow_cpu.cc
- src/cpu/flexcpu/simple_dataflow_thread.cc
- src/cpu/flexcpu/simple_dataflow_thread.hh
Change-Id: I81074541d5f028c09541ce09082e345f442349a3
> cpu-flex: Added alternative constraint to limit insts instead of ops.

- src/cpu/flexcpu/FlexCPU.py
- src/cpu/flexcpu/SConscript
- src/cpu/flexcpu/flexcpu.cc
- src/cpu/flexcpu/flexcpu.hh
- src/cpu/flexcpu/flexcpu_thread.cc
- src/cpu/flexcpu/flexcpu_thread.hh
cpu-flex: zero time microops
cpu-flex: simple_dataflow_cpu.hh slight reorganization for consistency
Change-Id: Ie07b94054b8149761703a549066fbf1022051dc8
> cpu-flex: Added configuration for zero-time microcode.

- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
Change-Id: Iafc8ba8c88d6bfe9b0e65c3f15d455231e0dcc46
> cpu-flex: Remove untested MIPS-specific code

- tests/gem5/cpu_tests/run.py
- tests/gem5/cpu_tests/test.py
Change-Id: I15946ce531def499a7afddc28d9027dabad0508f
> cpu-flex: Enable x86 tests for FlexCPU

- src/cpu/flexcpu/flexcpu.cc
- src/cpu/flexcpu/flexcpu.hh
- src/cpu/flexcpu/flexcpu_thread.cc
- src/cpu/flexcpu/flexcpu_thread.hh
- src/cpu/flexcpu/generic_reg.hh
- src/cpu/flexcpu/inflight_inst.cc
- src/cpu/flexcpu/inflight_inst.hh
- src/cpu/flexcpu/stld_forwarder.cc
- tests/gem5/cpu_tests/run.py
- tests/gem5/cpu_tests/test.py
- util/flexpipeviewer.py
I tested FlexCPU with microbench, Bubblesort and FloatMM. I used X86, ARM, and RISCV ISA, all of them work. I rebased FlexCPU to master in another branch, and all of them work as well.
> ARM integration 
